repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
            args: [--markdown-linebreak-ext=md]
          - id: check-json
          - id: check-yaml
          - id: check-ast
    - repo: https://github.com/pre-commit/mirrors-autopep8
      rev: v1.5.4
      hooks:
          - id: autopep8
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "v2.3.2"
      hooks:
          - id: prettier
            args: [--tab-width=4]
