service: comic-reader

useDotenv: true
# .env file need to contain
# bucket_name=Name of s3 bucket
# fsdb_root=Path to read comic from s3

frameworkVersion: "2"

provider:
    name: aws
    region: ap-northeast-1
    runtime: python3.8
    iamRoleStatements:
        - Effect: Allow
          Action:
              - s3:*
          Resource:
              - "arn:aws:s3:::${self:service}-bucket"
              - "arn:aws:s3:::${self:service}-bucket/*"

functions:
    api:
        handler: wsgi_handler.handler
        events:
            - http:
                  path: /
                  method: get
            - http:
                  path: comics
                  method: get
            - http:
                  path: episodeof/{comic_id}
                  method: get
            - http:
                  path: imageof/{comic_id}/{episode_id}
                  method: get

custom:
    wsgi:
        app: api.app
    s3Sync:
        - bucketName: ${self:service}-bucket
          bucketPrefix: comicdb/
          localDir: /PATH/TO/YOUR/COMICDIR
        - bucketName: ${self:service}-bucket
          localDir: ./frontend/

resources:
    Resources:
        AssetsBucket:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: ${self:service}-bucket

plugins:
    - serverless-python-requirements
    - serverless-dotenv-plugin
    - serverless-s3-sync
    - serverless-wsgi
