service: comic-reader

useDotenv: true
# .env file need to contain
# bucket_name=Name of s3 bucket
# fsdb_root=Path to read comic from s3

frameworkVersion: "1"

provider:
    name: aws
    region: ap-northeast-1
    runtime: python3.8

functions:
    api:
        handler: wsgi_handler.handler
        events:
            - http:
                  path: /
                  method: get
            - http:
                  path: comics
                  method: get
            - http:
                  path: episodeof/{comic_id}
                  method: get
            - http:
                  path: imageof/{comic_id}/{episode_id}
                  method: get

custom:
    wsgi:
        app: api.app
    s3Sync:
        - bucketName: comic-reader-bucket
          bucketPrefix: comicdb/
          localDir: ../section_6/testdb/
        - bucketName: comic-reader-bucket
          localDir: ./frontend/

resources:
    Resources:
        AssetsBucket:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: comic-reader-bucket

plugins:
    - serverless-python-requirements
    - serverless-dotenv-plugin
    - serverless-s3-sync
    - serverless-wsgi
