version: "3.3"

services:
    db:
        image: mysql:5.7
        command: |
            --default-authentication-plugin=mysql_native_password
            --character-set-server=utf8
            --collation-server=utf8_general_ci
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: toor
            MYSQL_DATABASE: comicdb
            MYSQL_USER: db_user
            MYSQL_PASSWORD: db_pass
        ports:
            - 3306:3306
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8081:80
